### Numpy

In [ ]:
Using NumPy create random vector of size 20 having only floating the range 1-20. 
Then reshape the array to 4 by 5
Then replace the max in each row by 0(axis=1)

In [16]:
import numpy as np

# generating the random 20 numbers using the numpy module
random_numbers=np.random.randint(1,20,20)
print("20 digits randome array ranging from 1-20 is: {}\n".format(random_numbers))

# Reshaping the array of elements into 4*5 matrix
reshape = random_numbers.reshape((4,5))
print("Reshaping the array to 4*5 matrix: \n{}\n".format(reshape))

'''' replacing  the max in each row by 0
 where(condition, if true this value , false this value)
 numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)'''

replace = np.where(reshape==np.amax(reshape,axis=1,keepdims=True),0,reshape)
print('Replacing the max in each row by 0: \n{}'.format(replace))

20 digits randome array ranging from 1-20 is: [ 7 11  7 12  7 10 14 16  9  5 16 10  8  6 17 13  3 18 10 16]

Reshaping the array to 4*5 matrix: 
[[ 7 11  7 12  7]
 [10 14 16  9  5]
 [16 10  8  6 17]
 [13  3 18 10 16]]

Replacing the max in each row by 0: 
[[ 7 11  7  0  7]
 [10 14  0  9  5]
 [16 10  8  6  0]
 [13  3  0 10 16]]
