### Numpy

In [ ]:
Using NumPy create random vector of size 20 having only floating the range 1-20. 
Then reshape the array to 4 by 5
Then replace the max in each row by 0(axis=1)

In [35]:
import numpy as np

# generating the random 20 numbers using the numpy module
random_numbers=np.random.uniform(1,20,20)
print("20 digits randome array ranging from 1-20 is: {}\n".format(random_numbers))

# Reshaping the array of elements into 4*5 matrix
reshape = random_numbers.reshape((4,5))
print("Reshaping the array to 4*5 matrix: \n{}\n".format(reshape))

'''' replacing  the max in each row by 0
 where(condition, if true this value , false this value)
 numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)'''

replace = np.where(reshape==np.amax(reshape,axis=1,keepdims=True),0,reshape)
print('Replacing the max in each row by 0: \n{}'.format(replace))

20 digits randome array ranging from 1-20 is: [13.17235222  3.45364259  5.89391114  1.83181806 11.09938395 19.72171676
  2.12225057  7.63957597  4.53706743 17.767945   14.42457226  7.47771978
 10.54447355  9.24331923 18.56367562 19.20923906 15.30020245  7.74076683
 17.05448315 15.21356891]

Reshaping the array to 4*5 matrix: 
[[13.17235222  3.45364259  5.89391114  1.83181806 11.09938395]
 [19.72171676  2.12225057  7.63957597  4.53706743 17.767945  ]
 [14.42457226  7.47771978 10.54447355  9.24331923 18.56367562]
 [19.20923906 15.30020245  7.74076683 17.05448315 15.21356891]]

Replacing the max in each row by 0: 
[[ 0.          3.45364259  5.89391114  1.83181806 11.09938395]
 [ 0.          2.12225057  7.63957597  4.53706743 17.767945  ]
 [14.42457226  7.47771978 10.54447355  9.24331923  0.        ]
 [ 0.         15.30020245  7.74076683 17.05448315 15.21356891]]
